options:
  assume_provider:
    type: boolean
    default: True
    description: "Assume a BIND server isntead of Recursive DNS provider"
  canonical_domain:
    type: string
    default: orangebox.com
    description: "Base Canonical Domain name for environment"
